spring:
  shardingsphere:
    datasource:
      names: ds-alibaba,ds-baidu
      ds-alibaba:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${fdf.datasource.url}:3306/demo_ds_alibaba?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
        username: ${fdf.datasource.username}
        password: ${fdf.datasource.password}
      ds-baidu:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${fdf.datasource.url}:3306/demo_ds_baidu?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
        username: ${fdf.datasource.username}
        password: ${fdf.datasource.password}
    sharding:
      default-database-strategy:
        inline:
          sharding-column: company_id
          algorithm-expression: ds-$->{company_id}
      tables:
        user:
          actual-data-nodes: ds-$->{['alibaba','baidu']}.user
          key-generator-column-name: id
    props:
      sql:
        show: true

