spring:
  shardingsphere:
    datasource:
      names: ds
      ds:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${fdf.datasource.url}:3306/demo_ds?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
        username: ${fdf.datasource.username}
        password: ${fdf.datasource.password}
    sharding:
      tables:
        user:
          actual-data-nodes: ds.user_$->{0..1}
          key-generator-column-name: id
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: user_$->{id % 2}
    props:
      sql:
        show: true

