server:
  port: 7300
# 暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
spring:
  application:
    name: code-generator
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/fdf?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.fandf.generator.model
fdf:
  swagger:
    enabled: true
    title: 自动生成代码
    base-package: com.fandf.generator.controller
    description: mybatis-plus自动生成代码
