spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/file_center?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.central.file.model
  global-config:
    db-config:
      id-type: INPUT

zlt:
  file-server:
    type: s3
    #fdfs:
    #  web-url: ${zlt.fdfs.web-url}
    s3:
      access-key: ${s3.access_key}
      accessKeySecret: ${s3.secret_key}
      endpoint: ${s3.endpoint}
      bucketName: ${s3.bucketName}
  swagger:
    enabled: true
    title: 文件中心
    description: 文件中心接口文档
    version: 1.0
    base-package: com.fandf.file.controller
  #多租户配置
  tenant:
    enable: true

#fastDFS配置
#fdfs:
#  soTimeout: 1500
#  connectTimeout: 600
#  trackerList: ${fdfs.trackerList}