server:
  port: 7200

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: log-center
  elasticsearch:
    rest:
      uris: 127.0.0.1:9200

fdf:
  swagger:
    enabled: true
    title: 日志中心
    description: 日志中心接口文档
    version: 1.0
    base-package: com.fandf.log.controller