server:
  port: 9900
spring:
  resources:
    #不加启动后 doc.html 404
    add-mappings: true
  application:
    name: fdf-gateway
  main:
    allow-bean-definition-overriding: true
  web:
    resources:
      add-mappings: false
  cloud:
    sentinel:
      datasource:
        #流量控制规则
        flow:
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: ${spring.application.name}-flow-rules
            groupId: SENTINEL_GROUP
            rule-type: flow
        #熔断降级规则
        degrade:
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: ${spring.application.name}-degrade-rules
            groupId: SENTINEL_GROUP
            rule-type: degrade
        system:
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: ${spring.application.name}-system-rules
            groupId: SENTINEL_GROUP
            rule-type: system
        #黑白名单控制
        authority:
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: ${spring.application.name}-authority-rules
            groupId: SENTINEL_GROUP
            rule-type: authority
        param-flow:
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: ${spring.application.name}-param-flow-rules
            groupId: SENTINEL_GROUP
            rule-type: param-flow
      eager: true
      transport:
        dashboard: localhost:8858
    gateway:
      discovery:
        locator:
          #路由的路径默认会使用大写ID，若想要使用小写ID，可将lowerCaseServiceId设置为true
          lower-case-service-id: true
          #网关自动根据注册中心的服务名为每个服务创建一个router
          enabled: true
      #          #不设置前缀默认ReactiveCompositeDiscoveryClient
      #          route-id-prefix: "fdf"
      routes:
        - id: generator
          uri: lb://code-generator
          predicates:
            - Path=/api-generator/**
          filters:
            - StripPrefix=1
        - id: search-center
          uri: lb://search-center
          predicates:
            - Path=/api-search/**
          filters:
            - StripPrefix=1
        - id: user-center
          uri: lb://user-center
          predicates:
            - Path=/api-user/**
          filters:
            - StripPrefix=1
        - id: auth
          uri: lb://uaa-server
          predicates:
            - Path=/api-uaa/**
          filters:
            - StripPrefix=1
            - PreserveHostHeader
        - id: auth-login-page
          uri: lb://uaa-server
          predicates:
            - Path=/login.html
          filters:
            - PreserveHostHeader
        - id: auth-login-process
          uri: lb://uaa-server
          predicates:
            - Path=/user/login
          filters:
            - PreserveHostHeader
        - id: auth-login-token
          uri: lb://uaa-server
          predicates:
            - Path=/oauth/token
          filters:
            - PreserveHostHeader
        - id: auth-login-authorize
          uri: lb://uaa-server
          predicates:
            - Path=/oauth/authorize
          filters:
            - PreserveHostHeader
        - id: auth-check-process
          uri: lb://uaa-server
          predicates:
            - Path=/oauth/check_token
          filters:
            - PreserveHostHeader
        - id: log
          uri: lb://log-center
          predicates:
            - Path=/api-log/**
          filters:
            - StripPrefix=1
fdf:
  trace:
    enable: true
  swagger-agg:
    generate-routes: auth,user-center,generator,search-center
  oauth2:
    token:
      store:
        type: redis
  security:
    ignore:
      # 忽略认证的地址
      httpUrls: >
        /*/v2/api-docs,
        /api-uaa/oauth/**,
        /api-uaa/validate/**,
        /api-uaa/css/**,
        /api-uaa/images/**,
        /api-uaa/js/**,
        /login.html,
        /user/login,
        /api-uaa/tokens/key
    auth:
      urlPermission:
        #是否开启url级别权限
        enable: false
        #配置只进行登录认证，不进行url权限认证的api
        ignoreUrls: >
          /api-user/menus/current,
          /api-user/users/current,
          /api-log/requestStat
        #白名单
        includeClientIds:
      #          - webApp
      renew:
        #是否开启token自动续签（目前只有redis实现）
        enable: true
        #白名单
        includeClientIds:
  #          - webApp
  gateway:
    #网关动态路由
    dynamicRoute:
      enabled: true